!TransformerTextEncoder
metas:
  on_gpu: true
  batch_size: 4
  workspace: $TMP_WORKSPACE
with:
  pooling_strategy: cls
  backend: pytorch
  max_length: 8
requests:
  on:
    [SearchRequest, IndexRequest]:
      - !EncodeDriver
        with:
          method: encode

    ControlRequest:
      - !ControlReqDriver {}